# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95db46c285591e11617a277e9adba17bda5709007dc016457991f4727d59cc1e4e47805c182cff893095f42b72ac98644a009b98c58dcf607f8941a5ac9143c9

test:
  secret_key_base: d924e58a8c73b2aef239b29a0414fa86bdee01253192662a70b020a1908f7605831da66657a334399e2cca01366c6da76b3b765975ddc7660375e32236911d97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
